openapi: 3.0.0
info:
  title: cardAcceptors
  version: '1.0'
  description: A backend service to enable a cloud orchestrated Terminal solution for POS systems
  contact:
    name: Salt Group
servers:
  - url: 'http://localhost:3100'
paths:
  /cardAcceptors:
    post:
      summary: Create  card acceptor auth account
      operationId: createCardAcceptorAuthAccount
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  message:
                    type: string
                  cardAcceptorDetails:
                    type: object
                    properties:
                      cardAcceptorGuid:
                        type: string
                    required:
                      - cardAcceptorGuid
      tags:
        - cardAcceptor
      description: Each card acceptor created within the portal will require system credentials that APIs may use to authenticate on behalf of the card acceptor. The credentials are created in Fusion Auth with a preset creation definition.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                mid:
                  type: string
                acquirer:
                  type: string
                tmsAccessToken:
                  type: string
              required:
                - mid
                - acquirer
        description: MID for the card acceptor auth account being created
components:
  schemas: {}
  securitySchemes:
    Authorization:
      type: http
      scheme: bearer
      description: ''
tags:
  - name: cardAcceptor
    description: Administer the card acceptors managed by the service
    externalDocs:
      url: 'http://terminals.somewhere.com/admin.htm'
  - name: admin
    description: Administer the terminals managed by the service
    externalDocs:
      url: 'http://terminals.somewhere.com/admin.htm'
  - name: pos
    description: Methods available to POS systems
    externalDocs:
      url: 'http://terminals.somewhere.com/pos.htm'
  - name: terminal
    description: Methods available to terminals
    externalDocs:
      url: 'http://terminals.somewhere.com/terminals.htm'
  - name: model
    description: Data models used by the API
    externalDocs:
      url: 'http://terminals.somewhere.com/models.htm'
