openapi: 3.0.0
info:
  title: Card Acceptors
  version: '1.0'
  description: A backend module to enable a cloud orchestrated Terminal solution for POS systems
  contact:
    name: SaltPay Group
servers:
  - url: 'http://localhost:3100'
paths:
  /card_acceptors:
    post:
      summary: Create card acceptor auth account
      operationId: createCardAcceptorAuthAccount
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CardAcceptorCreateResponse'
      description: Each card acceptor created within the portal will require system credentials that APIs may use to authenticate on behalf of the card acceptor. The credentials are created in Fusion Auth with a preset creation definition.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                partnerGuid:
                  type: string
                  description: Optional for backwards compatibility for now. Will default to service configured value if not provided.
                acquirer:
                  type: string
                mid:
                  type: string
                name:
                  type: string
                switchAccessToken:
                  type: string
                address:
                  $ref: '#/components/schemas/Address'
                subDivision:
                  type: string
                  description: 'ISO 3166-2 Standard Sub Division '
                  minLength: 1
                  maxLength: 10
                country:
                  type: string
                phoneNumber:
                  type: string
                mcc:
                  type: integer
              required:
                - acquirer
                - mid
                - name
        description: MID for the card acceptor auth account being created
      tags:
        - admin
    parameters: []
    get:
      summary: Get Card Acceptors
      operationId: getCardAcceptors
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CardAcceptorInfoListResponse'
      description: |-
        Retrieve a list of card acceptors linked to the provided JWT. Optionally filtered by the fields provided.

        Only supported for POS, ADMIN and ONBOARDING applications.
      security:
        - Authorization: []
      parameters:
        - schema:
            type: string
          in: query
          name: mid
      tags:
        - admin
  '/card_acceptors/{cardAcceptorGuid}/manager_pin':
    parameters:
      - schema:
          type: string
        name: cardAcceptorGuid
        in: path
        required: true
    post:
      summary: Set Manager Pin
      operationId: setCardAcceptorManagerPin
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  message:
                    type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties: {}
      tags:
        - terminal
      description: Set the pin for a card acceptor
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                managerPinData:
                  type: string
              required:
                - managerPinData
      security:
        - Authorization: []
      parameters:
        - schema:
            type: string
          in: query
          name: locale
    put:
      summary: Update Manager Pin
      operationId: updateCardAcceptorManagerPin
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  message:
                    type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  message:
                    type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                managerPinData:
                  type: string
      parameters:
        - schema:
            type: string
          in: header
          name: x-managerPinData
          description: ''
      description: Update the pin for a specific card acceptor
      tags:
        - admin
      security:
        - Authorization: []
  '/card_acceptors/{cardAcceptorGuid}':
    parameters:
      - schema:
          type: string
        name: cardAcceptorGuid
        in: path
        required: true
    patch:
      summary: Update Card Acceptor
      operationId: updateCardAcceptor
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CardAcceptorDetailsResponse'
        '404':
          description: Card Acceptor Not Found
          content:
            application/json:
              schema:
                $ref: ./terminals.v1.yaml#/components/schemas/ApiResponse
      description: |-
        Update the card acceptor record with latest details needed by the terminal. This includes the optional Loyalty Program details. If Loyalty Program details are provided, this call will operate within a transaction, during which it will also call the Loyalty Gateway service to update its Card Acceptor with the Loyalty Program linked to the Card Acceptor. If this call fails, the change will be rolled back.

        When updating the featureConfig field, the entire field must be provided as the entire field will be replaced if it is present.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CardAcceptorUpdateRequest'
      tags:
        - admin
    get:
      summary: Get Card Acceptor By Guid
      operationId: getCardAcceptorByGuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CardAcceptorDetailsResponse'
      description: Get the full details of a single card acceptor using its guid. Only available to an ADMIN application.
      tags:
        - admin
      security:
        - Authorization: []
  '/card_acceptors/{cardAcceptorGuid}/loyalty_program':
    parameters:
      - schema:
          type: string
        name: cardAcceptorGuid
        in: path
        required: true
    delete:
      summary: Unlink Loyalty Program
      operationId: unlinkCardAcceptorLoyalty
      responses:
        '200':
          description: OK
        '404':
          description: Card Acceptor not found
      tags:
        - admin
      description: This call can be made with an ADMIN or ONBOARDING application JWT to clear the loyalty program and related configuration from the card acceptor.
      security:
        - Authorization: []
  '/card_acceptors/{cardAcceptorGuid}/pos':
    parameters:
      - schema:
          type: string
        name: cardAcceptorGuid
        in: path
        required: true
    delete:
      summary: Unlink POS
      operationId: unlinkCardAcceptorPos
      responses:
        '200':
          description: OK
        '404':
          description: Card Acceptor not found
      description: 'This call can be made with an ADMIN or ONBOARDING application JWT to clear the POS related configuration from the card acceptor. If there is no POS, return 200 OK.'
      parameters: []
      security:
        - Authorization: []
      tags:
        - admin
  '/card_acceptors/{cardAcceptorGuid}/authorised_card_acceptors':
    parameters:
      - schema:
          type: string
        name: cardAcceptorGuid
        in: path
        required: true
    post:
      summary: Add Authorised Card Acceptor
      operationId: addAuthorisedCardAcceptors
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models.v1.yaml#/components/schemas/ApiResponse
      description: This call can be made with an ADMIN or ONBOARDING application JWT to add an authorised card acceptor for the owner card acceptor as identified in the path.
      tags:
        - admin
      security:
        - Authorization: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./models.v1.yaml#/components/schemas/AuthorisedCardAcceptorRequest
    get:
      summary: Get Authorised Card Acceptors
      operationId: getAuthorisedCardAcceptors
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models.v1.yaml#/components/schemas/AuthorisedCardAcceptorListResponse
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ./models.v1.yaml#/components/schemas/ApiResponse
        '404':
          description: Owner Card Acceptor Not Found
          content:
            application/json:
              schema:
                $ref: ./models.v1.yaml#/components/schemas/ApiResponse
      security:
        - Authorization: []
      description: This call can be made with an ADMIN or ONBOARDING application JWT to retrieve the list of active authorised card acceptors for an owner card acceptor as identified in the path.
      tags:
        - admin
  '/card_acceptors/{cardAcceptorGuid}/authorised_card_acceptors/{authorisedCardAcceptorGuid}':
    parameters:
      - schema:
          type: string
        name: cardAcceptorGuid
        in: path
        required: true
      - schema:
          type: string
        name: authorisedCardAcceptorGuid
        in: path
        required: true
    delete:
      summary: Remove Authorised Card Acceptor
      operationId: removeAuthorisedCardAcceptor
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models.v1.yaml#/components/schemas/ApiResponse
        '404':
          description: 'Owner or Authorised Card Acceptor Not Found. However, these cases will have different response codes.'
          content:
            application/json:
              schema:
                $ref: ./models.v1.yaml#/components/schemas/ApiResponse
      tags:
        - admin
      description: This call can be made with an ADMIN or ONBOARDING application JWT to disable an authorised card acceptor for the owner card acceptor as identified in the path. The entry is not removed from the database as this would cause issues with data replication and reporting. Instead the entry's state is marked as inactive.
      security:
        - Authorization: []
components:
  schemas:
    CardAcceptorDetails:
      title: CardAcceptorDetails
      type: object
      description: Object describing the full set of details available for a card acceptor. The actual set will depend on what is avaiable at the time and may be dependent on the caller.
      properties:
        cardAcceptorGuid:
          type: string
        acquirer:
          type: string
        mid:
          type: string
        name:
          type: string
        managerPinSet:
          type: boolean
        switchAccessToken:
          type: string
        posGuid:
          type: string
        loyaltyProgramGuid:
          type: string
        state:
          type: string
        featureConfig:
          $ref: ./partners.v1.yaml#/components/schemas/FeatureConfig
        address:
          $ref: '#/components/schemas/Address'
        subDivision:
          type: string
          description: 'ISO 3166-2 Standard Sub Division '
          minLength: 1
          maxLength: 10
        country:
          type: string
        phoneNumber:
          type: string
        mcc:
          type: integer
    CardAcceptorCreateDetails:
      title: CardAcceptorCreateDetails
      type: object
      description: Object describing the set of details available for a card acceptor after creation.
      properties:
        cardAcceptorGuid:
          type: string
      required:
        - cardAcceptorGuid
    CardAcceptorDetailsResponse:
      title: CardAcceptorDetailsResponse
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
        cardAcceptorDetails:
          $ref: '#/components/schemas/CardAcceptorDetails'
    CardAcceptorCreateResponse:
      title: CardAcceptorCreateResponse
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
        cardAcceptorDetails:
          $ref: '#/components/schemas/CardAcceptorCreateDetails'
    CardAcceptorInfo:
      title: CardAcceptorInfo
      type: object
      properties:
        cardAcceptorGuid:
          type: string
        acquirer:
          type: string
        mid:
          type: string
        name:
          type: string
        state:
          type: string
        featureConfig:
          $ref: ./partners.v1.yaml#/components/schemas/FeatureConfig
    CardAcceptorInfoListResponse:
      title: CardAcceptorInfoListResponse
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
        cardAcceptorDetailsList:
          type: array
          items:
            $ref: '#/components/schemas/CardAcceptorInfo'
    CardAcceptorUpdateRequest:
      title: CardAcceptorUpdateRequest
      type: object
      properties:
        switchAccessToken:
          type: string
        name:
          type: string
        loyaltyProgramGuid:
          type: string
        loyaltyAccessToken:
          type: string
        featureConfig:
          $ref: ./partners.v1.yaml#/components/schemas/FeatureConfig
        address:
          $ref: '#/components/schemas/Address'
        subDivision:
          type: string
          description: 'ISO 3166-2 Standard Sub Division '
          minLength: 0
          maxLength: 10
        country:
          type: string
        phoneNumber:
          type: string
        mcc:
          type: integer
    Address:
      title: Address
      type: object
      description: Object describing a CardAcceptor/Merchant's physical address
      properties:
        line1:
          type: string
        line2:
          type: string
        city:
          type: string
        postalCode:
          type: string
  securitySchemes:
    Authorization:
      type: http
      scheme: bearer
      description: ''
tags:
  - name: cardAcceptor
    description: Administer the card acceptors managed by the service
  - name: admin
    description: Administer the terminals managed by the service
  - name: pos
    description: Methods available to POS systems
  - name: terminal
    description: Methods available to terminals
  - name: model
    description: Data models used by the API
