openapi: 3.0.0
info:
  title: webhooks
  version: '1.0'
  description: A backend service to enable managment of point of sale providers
  contact:
    name: Salt Group
servers:
  - url: 'http://localhost:3000'
paths:
  /card_acceptors:
    post:
      summary: Register card acceptor
      operationId: createCardAcceptor
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                  message:
                    type: string
                  posDetails:
                    type: object
                    properties:
                      posGuid:
                        type: string
                    required:
                      - posGuid
      description: Register new card acceptor with POS provider when a new card acceptor is onboarded
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/posDetailsRequest'
        description: ''
      tags:
        - pos
    parameters: []
components:
  schemas:
    ApiResponse:
      title: ApiResponse
      type: object
      description: 'Base API response object used for all API responses. This can include cases when there are server errors, as the responseCode allows for finer grained error reporting than the HTTP status alone.'
      properties:
        code:
          type: number
        message:
          type: string
    posDetailsRequest:
      title: posDetailsRequest
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        companyWebsite:
          type: string
        supportEmail:
          type: string
        supportPhone:
          type: string
        webhookUrl:
          type: string
        webhookType:
          type: string
          enum:
            - rest
          description: type of callback system being supported
      required:
        - name
        - description
    cardAcceptorDetails:
      title: cardAcceptorDetails
      type: object
      properties:
        cardAcceptorGuid:
          type: string
        companyRegistrationNumber:
          type: string
  securitySchemes:
    Authorization:
      type: http
      scheme: bearer
      description: ''
tags:
  - name: cardAcceptor
    description: Administer the card acceptors managed by the service
    externalDocs:
      url: 'http://terminals.somewhere.com/admin.htm'
  - name: admin
    description: Administer the terminals managed by the service
    externalDocs:
      url: 'http://terminals.somewhere.com/admin.htm'
  - name: pos
    description: Methods available to POS systems
    externalDocs:
      url: 'http://terminals.somewhere.com/pos.htm'
  - name: terminal
    description: Methods available to terminals
    externalDocs:
      url: 'http://terminals.somewhere.com/terminals.htm'
  - name: model
    description: Data models used by the API
    externalDocs:
      url: 'http://terminals.somewhere.com/models.htm'
