openapi: 3.0.0
info:
  title: webhooks
  version: '1.0'
  description: A backend service to enable managment of point of sale providers
  contact:
    name: Salt Group
servers:
  - url: 'http://localhost:3000'
paths:
  /cardAcceptors:
    post:
      summary: Register card acceptor
      operationId: createCardAcceptor
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  message:
                    type: string
                  listOfLocations:
                    type: array
                    items:
                      $ref: './pos.v1.yaml#/components/schemas/posLocations'
                required:
                  - code
                  - message
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  message:
                    type: string
      description: Register new card acceptor with POS provider when a new card acceptor is onboarded
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                companyRegistrationNumber:
                  type: string
                posLocationId:
                  type: string
                cardAcceptorGuid:
                  type: string
              required:
                - companyRegistrationNumber
                - cardAcceptorGuid
        description: ''
      tags:
        - pos
    parameters: []
  /terminals:
    post:
      summary: Terminal Link Notification
      operationId: terminalsNotification
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: -1
                    description: '-1 for success'
                  message:
                    type: string
      description: A post to notify POS provider that a terminal has been linked to a cardAcceptor. The link could be for a new temrinal at the cardAcceptor or a re-link of a terminal.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                terminalGuid:
                  type: string
                description:
                  type: string
                brand:
                  type: string
                model:
                  type: string
                serialNumber:
                  type: string
      tags:
        - webhooks
components:
  schemas: {}
  securitySchemes:
    Authorization:
      type: http
      scheme: bearer
      description: ''
tags:
  - name: cardAcceptor
    description: Administer the card acceptors managed by the service
    externalDocs:
      url: 'http://terminals.somewhere.com/admin.htm'
  - name: admin
    description: Administer the terminals managed by the service
    externalDocs:
      url: 'http://terminals.somewhere.com/admin.htm'
  - name: pos
    description: Methods available to POS systems
    externalDocs:
      url: 'http://terminals.somewhere.com/pos.htm'
  - name: terminal
    description: Methods available to terminals
    externalDocs:
      url: 'http://terminals.somewhere.com/terminals.htm'
  - name: model
    description: Data models used by the API
    externalDocs:
      url: 'http://terminals.somewhere.com/models.htm'
  - name: webhooks
    description: Webhooks to be supply by third party consumers
    externalDocs:
      url: 'http://terminals.somewhere.com/webhooks.htm'
